[project]
name = "tetris-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.11.0.86",
    "stable-baselines3>=2.7.1",
    "tetris-gymnasium>=0.3.0",
]
